"""Tests for generated human-facing phase checkpoint documents."""

from __future__ import annotations

import textwrap
from pathlib import Path

from gpd.core.checkpoints import sync_phase_checkpoints

_GENERATED_HEADER = "<!-- Generated by gpd sync-phase-checkpoints. Do not edit by hand. -->"


def _setup_project(tmp_path: Path) -> Path:
    planning = tmp_path / ".gpd" / "phases"
    planning.mkdir(parents=True)
    return tmp_path


def _write_summary(
    path: Path,
    *,
    phase: str,
    plan: str,
    one_liner: str,
    completed: str = "2026-03-17",
    provides: str | list[str] = "phase checkpoint",
) -> None:
    lines = [
        "---",
        f'phase: "{phase}"',
        f'plan: "{plan}"',
        "depth: full",
    ]
    if isinstance(provides, list):
        lines.append("provides:")
        lines.extend(f"  - {item}" for item in provides)
    else:
        lines.append(f"provides: {provides!r}")
    lines.extend(
        [
            f'completed: "{completed}"',
            f'one-liner: "{one_liner}"',
            "key-files:",
            "  - src/model.py",
            "key-decisions:",
            "  - Keep the reduced wedge",
            "patterns-established:",
            "  - Hidden-damage rejection survives",
            "---",
            "",
            "# Summary",
            "",
            f"**{one_liner}**",
            "",
            "## Key Results",
            "",
            "The phase produced a clean checkpoint result.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_malformed_summary(path: Path, *, phase: str, plan: str) -> None:
    path.write_text(
        textwrap.dedent(
            f"""\
            ---
            phase: "{phase}"
            plan: "{plan}"
            completed: "2026-03-17"
            one-liner: "Broken summary"
            key-files:
              - src/model.py
            key-decisions:
              - Keep the reduced wedge
            patterns-established:
              - Hidden-damage rejection survives
            invalid: [unterminated
            ---

            # Summary
            """
        ),
        encoding="utf-8",
    )


def _write_generated_checkpoint(path: Path, title: str) -> None:
    path.write_text(
        textwrap.dedent(
            f"""\
            {_GENERATED_HEADER}

            # {title}
            """
        ),
        encoding="utf-8",
    )


def test_sync_phase_checkpoints_generates_root_and_phase_docs(tmp_path: Path) -> None:
    cwd = _setup_project(tmp_path)
    phase_dir = cwd / ".gpd" / "phases" / "01-test-phase"
    phase_dir.mkdir()
    _write_summary(phase_dir / "01-SUMMARY.md", phase="01", plan="01", one_liner="Set up the project")
    (phase_dir / "01-VERIFICATION.md").write_text("# Verification\n\nPassed.\n", encoding="utf-8")

    result = sync_phase_checkpoints(cwd)

    assert result.generated is True
    assert result.phase_count == 1
    assert result.preserved_phase_count == 0
    assert ".gpd/phase-checkpoints/01-test-phase.md" in result.updated_files
    assert ".gpd/CHECKPOINTS.md" in result.updated_files

    phase_checkpoint = (cwd / ".gpd" / "phase-checkpoints" / "01-test-phase.md").read_text(encoding="utf-8")
    assert "# Phase 01 Checkpoint" in phase_checkpoint
    assert "[01-SUMMARY.md](../phases/01-test-phase/01-SUMMARY.md)" in phase_checkpoint
    assert "[01-VERIFICATION.md](../phases/01-test-phase/01-VERIFICATION.md)" in phase_checkpoint
    assert "The headline result was straightforward" in phase_checkpoint

    checkpoints_index = (cwd / ".gpd" / "CHECKPOINTS.md").read_text(encoding="utf-8")
    assert "[Phase 01: Test Phase](phase-checkpoints/01-test-phase.md)" in checkpoints_index
    assert "\\" not in phase_checkpoint
    assert "\\" not in checkpoints_index

    rerun = sync_phase_checkpoints(cwd)
    assert rerun.updated_files == []
    assert rerun.removed_files == []


def test_sync_phase_checkpoints_preserves_scalar_provides(tmp_path: Path) -> None:
    cwd = _setup_project(tmp_path)
    phase_dir = cwd / ".gpd" / "phases" / "01-test-phase"
    phase_dir.mkdir()
    _write_summary(
        phase_dir / "01-SUMMARY.md",
        phase="01",
        plan="01",
        one_liner="Set up the project",
        provides="solver",
    )

    result = sync_phase_checkpoints(cwd)

    assert result.phase_count == 1
    phase_checkpoint = (cwd / ".gpd" / "phase-checkpoints" / "01-test-phase.md").read_text(encoding="utf-8")
    assert "In practical terms, this phase now gives the project solver." in phase_checkpoint


def test_sync_phase_checkpoints_skips_malformed_summary_and_still_regenerates_other_phases(
    tmp_path: Path,
) -> None:
    cwd = _setup_project(tmp_path)

    good_phase_dir = cwd / ".gpd" / "phases" / "01-good-phase"
    good_phase_dir.mkdir()
    _write_summary(good_phase_dir / "01-SUMMARY.md", phase="01", plan="01", one_liner="Set up the project")
    (good_phase_dir / "01-VERIFICATION.md").write_text("# Verification\n\nPassed.\n", encoding="utf-8")

    bad_phase_dir = cwd / ".gpd" / "phases" / "02-bad-phase"
    bad_phase_dir.mkdir()
    _write_malformed_summary(bad_phase_dir / "01-SUMMARY.md", phase="02", plan="01")

    result = sync_phase_checkpoints(cwd)

    assert result.phase_count == 1
    assert result.preserved_phase_count == 0
    assert "Skipped .gpd/phases/02-bad-phase/01-SUMMARY.md: malformed frontmatter" in "\n".join(result.errors)
    assert ".gpd/phase-checkpoints/01-good-phase.md" in result.updated_files
    assert ".gpd/CHECKPOINTS.md" in result.updated_files
    assert not (cwd / ".gpd" / "phase-checkpoints" / "02-bad-phase.md").exists()

    good_checkpoint = (cwd / ".gpd" / "phase-checkpoints" / "01-good-phase.md").read_text(encoding="utf-8")
    checkpoints_index = (cwd / ".gpd" / "CHECKPOINTS.md").read_text(encoding="utf-8")

    assert "# Phase 01 Checkpoint" in good_checkpoint
    assert "[01-SUMMARY.md](../phases/01-good-phase/01-SUMMARY.md)" in good_checkpoint
    assert "[Phase 01: Good Phase](phase-checkpoints/01-good-phase.md)" in checkpoints_index
    assert "Phase 02" not in checkpoints_index
    assert "\\" not in good_checkpoint
    assert "\\" not in checkpoints_index


def test_sync_phase_checkpoints_preserves_existing_generated_output_for_unreadable_summary(
    tmp_path: Path,
) -> None:
    cwd = _setup_project(tmp_path)

    good_phase_dir = cwd / ".gpd" / "phases" / "01-good-phase"
    good_phase_dir.mkdir()
    _write_summary(good_phase_dir / "01-SUMMARY.md", phase="01", plan="01", one_liner="Set up the project")
    (good_phase_dir / "01-VERIFICATION.md").write_text("# Verification\n\nPassed.\n", encoding="utf-8")

    bad_phase_dir = cwd / ".gpd" / "phases" / "02-binary-phase"
    bad_phase_dir.mkdir()
    (bad_phase_dir / "01-SUMMARY.md").write_bytes(b"\x80\x81\x82")

    checkpoint_dir = cwd / ".gpd" / "phase-checkpoints"
    checkpoint_dir.mkdir()
    preserved = checkpoint_dir / "02-binary-phase.md"
    _write_generated_checkpoint(preserved, "Phase 02 Checkpoint")

    result = sync_phase_checkpoints(cwd)

    assert result.phase_count == 1
    assert result.preserved_phase_count == 1
    assert "Skipped .gpd/phases/02-binary-phase/01-SUMMARY.md: unreadable or missing file" in "\n".join(result.errors)
    assert preserved.exists()
    assert preserved.read_text(encoding="utf-8").startswith(_GENERATED_HEADER)
    assert ".gpd/phase-checkpoints/02-binary-phase.md" not in result.removed_files
    assert ".gpd/phase-checkpoints/01-good-phase.md" in result.updated_files
    checkpoints_index = (cwd / ".gpd" / "CHECKPOINTS.md").read_text(encoding="utf-8")
    assert "[Phase 02: Binary Phase](phase-checkpoints/02-binary-phase.md)" in checkpoints_index


def test_sync_phase_checkpoints_uses_latest_summary_and_keeps_earlier_notes(tmp_path: Path) -> None:
    cwd = _setup_project(tmp_path)
    phase_dir = cwd / ".gpd" / "phases" / "02-two-step-phase"
    phase_dir.mkdir()
    _write_summary(phase_dir / "01-SUMMARY.md", phase="02", plan="01", one_liner="Built the first draft")
    _write_summary(phase_dir / "02-SUMMARY.md", phase="02", plan="02", one_liner="Refined the final result")

    sync_phase_checkpoints(cwd)

    phase_checkpoint = (cwd / ".gpd" / "phase-checkpoints" / "02-two-step-phase.md").read_text(encoding="utf-8")
    assert "Refined the final result" in phase_checkpoint
    assert "## Earlier Plan Notes" in phase_checkpoint
    assert "Built the first draft." in phase_checkpoint


def test_sync_phase_checkpoints_removes_stale_checkpoint_docs(tmp_path: Path) -> None:
    cwd = _setup_project(tmp_path)
    phase_dir = cwd / ".gpd" / "phases" / "03-real-phase"
    phase_dir.mkdir()
    _write_summary(phase_dir / "01-SUMMARY.md", phase="03", plan="01", one_liner="Closed the phase")

    checkpoint_dir = cwd / ".gpd" / "phase-checkpoints"
    checkpoint_dir.mkdir()
    stale = checkpoint_dir / "99-old-phase.md"
    _write_generated_checkpoint(stale, "Phase 99 Checkpoint")

    result = sync_phase_checkpoints(cwd)

    assert ".gpd/phase-checkpoints/99-old-phase.md" in result.removed_files
    assert stale.exists() is False


def test_sync_phase_checkpoints_does_not_create_empty_outputs_when_no_summaries_exist(tmp_path: Path) -> None:
    cwd = _setup_project(tmp_path)
    (cwd / ".gpd" / "phases" / "01-empty-phase").mkdir()

    result = sync_phase_checkpoints(cwd)

    checkpoint_dir = cwd / ".gpd" / "phase-checkpoints"

    assert result.phase_count == 0
    assert result.preserved_phase_count == 0
    assert result.generated is False
    assert result.updated_files == []
    assert result.removed_files == []
    assert not (cwd / ".gpd" / "CHECKPOINTS.md").exists()
    assert not checkpoint_dir.exists()


def test_sync_phase_checkpoints_preserves_unmanaged_markdown_and_cleans_generated_outputs_when_nothing_remains(
    tmp_path: Path,
) -> None:
    cwd = _setup_project(tmp_path)
    (cwd / ".gpd" / "phases" / "01-empty-phase").mkdir()

    checkpoint_dir = cwd / ".gpd" / "phase-checkpoints"
    checkpoint_dir.mkdir()
    generated = checkpoint_dir / "01-empty-phase.md"
    _write_generated_checkpoint(generated, "Phase 01 Checkpoint")
    unmanaged = checkpoint_dir / "notes.md"
    unmanaged.write_text("# keep me\n", encoding="utf-8")
    root_index = cwd / ".gpd" / "CHECKPOINTS.md"
    _write_generated_checkpoint(root_index, "Phase Checkpoints")

    result = sync_phase_checkpoints(cwd)

    assert result.phase_count == 0
    assert result.preserved_phase_count == 0
    assert ".gpd/phase-checkpoints/01-empty-phase.md" in result.removed_files
    assert ".gpd/CHECKPOINTS.md" in result.removed_files
    assert generated.exists() is False
    assert unmanaged.exists()
    assert unmanaged.read_text(encoding="utf-8") == "# keep me\n"
    assert root_index.exists() is False


def test_sync_phase_checkpoints_keeps_existing_generated_outputs_for_failed_phase_and_cleans_empty_dir(
    tmp_path: Path,
) -> None:
    cwd = _setup_project(tmp_path)
    (cwd / ".gpd" / "phases" / "01-bad-phase").mkdir()
    (cwd / ".gpd" / "phases" / "01-bad-phase" / "01-SUMMARY.md").write_bytes(b"\x80\x81\x82")

    checkpoint_dir = cwd / ".gpd" / "phase-checkpoints"
    checkpoint_dir.mkdir()
    preserved = checkpoint_dir / "01-bad-phase.md"
    _write_generated_checkpoint(preserved, "Phase 01 Checkpoint")

    result = sync_phase_checkpoints(cwd)

    assert result.phase_count == 0
    assert result.preserved_phase_count == 1
    assert result.generated is True
    assert preserved.exists()
    assert ".gpd/phase-checkpoints/01-bad-phase.md" not in result.removed_files
    assert (cwd / ".gpd" / "CHECKPOINTS.md").exists()
