"""LaTeX paper-building utilities for GPD."""

from gpd.mcp.paper.bibliography import (
    BibliographyAudit,
    CitationAuditRecord,
    CitationSource,
    build_bibliography,
    build_bibliography_with_audit,
    write_bibliography_audit,
)
from gpd.mcp.paper.compiler import build_paper, compile_paper
from gpd.mcp.paper.journal_map import get_journal_for_domain, get_journal_spec, list_journals
from gpd.mcp.paper.models import (
    ArtifactManifest,
    ArtifactRecord,
    ArtifactSourceRef,
    Author,
    ClaimIndex,
    ClaimRecord,
    ClaimType,
    FigureRef,
    JournalSpec,
    PaperConfig,
    PaperOutput,
    ReviewConfidence,
    ReviewFinding,
    ReviewIssue,
    ReviewIssueSeverity,
    ReviewIssueStatus,
    ReviewLedger,
    ReviewPanelBundle,
    ReviewRecommendation,
    ReviewStageKind,
    ReviewSupportStatus,
    Section,
    StageReviewReport,
)
from gpd.mcp.paper.review_artifacts import (
    read_claim_index,
    read_review_ledger,
    read_review_panel_bundle,
    read_stage_review_report,
    write_claim_index,
    write_review_ledger,
    write_review_panel_bundle,
    write_stage_review_report,
)

__all__ = [
    "Author",
    "ArtifactManifest",
    "ArtifactRecord",
    "ArtifactSourceRef",
    "BibliographyAudit",
    "ClaimIndex",
    "ClaimRecord",
    "ClaimType",
    "CitationAuditRecord",
    "CitationSource",
    "FigureRef",
    "JournalSpec",
    "PaperConfig",
    "PaperOutput",
    "ReviewConfidence",
    "ReviewFinding",
    "ReviewIssue",
    "ReviewIssueSeverity",
    "ReviewIssueStatus",
    "ReviewLedger",
    "ReviewPanelBundle",
    "ReviewRecommendation",
    "ReviewStageKind",
    "ReviewSupportStatus",
    "Section",
    "StageReviewReport",
    "build_bibliography",
    "build_bibliography_with_audit",
    "build_paper",
    "compile_paper",
    "get_journal_for_domain",
    "get_journal_spec",
    "list_journals",
    "read_claim_index",
    "read_review_ledger",
    "read_review_panel_bundle",
    "read_stage_review_report",
    "write_bibliography_audit",
    "write_claim_index",
    "write_review_ledger",
    "write_review_panel_bundle",
    "write_stage_review_report",
]
