"""Shared constants for knowledge-document lifecycle values."""

KNOWLEDGE_STATUS_DRAFT = "draft"
KNOWLEDGE_STATUS_IN_REVIEW = "in_review"
KNOWLEDGE_STATUS_STABLE = "stable"
KNOWLEDGE_STATUS_SUPERSEDED = "superseded"
KNOWLEDGE_STATUS_VALUES = (
    KNOWLEDGE_STATUS_DRAFT,
    KNOWLEDGE_STATUS_IN_REVIEW,
    KNOWLEDGE_STATUS_STABLE,
    KNOWLEDGE_STATUS_SUPERSEDED,
)

KNOWLEDGE_REVIEW_DECISION_APPROVED = "approved"
KNOWLEDGE_REVIEW_DECISION_NEEDS_CHANGES = "needs_changes"
KNOWLEDGE_REVIEW_DECISION_REJECTED = "rejected"
KNOWLEDGE_REVIEW_DECISION_VALUES = (
    KNOWLEDGE_REVIEW_DECISION_APPROVED,
    KNOWLEDGE_REVIEW_DECISION_NEEDS_CHANGES,
    KNOWLEDGE_REVIEW_DECISION_REJECTED,
)

